name: biodivcao
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.6
  - snakemake-minimal=7.18.2
  - pandas=1.5.0
  - snakefmt=0.6.1
  - biopython=1.81
  - ete3=3.1.2
  - tqdm
  - mamba
