name: biodivcao
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.6
  - snakemake-minimal=7.32.4
  - pandas=1.5.0
  - snakefmt=0.6.1
  - biopython=1.81
  - ete3=3.1.2
  - coverm=0.6.1
  - vsearch=2.21.2
  - tqdm
  - mamba
