default-resources: "slurm_account=naiss2023-5-209"
#default-resources: "mem_mb=6400"
slurm: "True"
rerun-triggers: "mtime"
rerun-incomplete: "True"
reason: "True"
keep-going: "True"
cluster-cancel: "scancel"
local-cores: 1
latency-wait: "5"
use-conda: "False"
use-singularity: "False"
use-envmodules: "True"
jobs: "500"
printshellcmds: "True"
cores: 20
