# configuration file for project
sample_list : "config/central_arctic_ocean.csv"
results_dir: "results"
mappers:
  - "minimap2"
fastp :
  settings: ""
  complexity_threshold : 30
mappings_list : "config/mappings.csv"
# Specify library type to map against genomes database
lib_type_to_map: ["DNA"]
mappings:
  genomes:
    target_species:
      fasta: "resources/genome_index/all_verts_whuman/all_verts_whuman.fasta"
      taxon_table: "resources/genome_index/all_verts_whuman/taxon_table.csv"
      to_include: "resources/genome_index/all_verts_whuman/to_include.bed"

blast:
  db: "/sw/data/blast_databases/nt"
  evalue: 1e-30
  max_target_seqs: 200

krakenuniq:
  db: "/sw/data/KrakenUniq_data/prebuilt/krakendb-2022-06-16-STANDARD"
  exclude: [2,2157,9604]

bowtie2:
  threads: 20

minimap2:
  threads: 20
  split_num: 4

sintax:
  cutoff: 0.8
  ranks: [ "kingdom", "phylum", "class", "order", "family", "genus", "species" ]
  replace_ranks: [ "kingdom=kingdom", "phylum=phylum", "class=class", "order=order", "family=family", "genus=genus", "species=species"]
  db: "resources/coinr/COInr.sintax.fasta"

coinr:
  dbname: "COInr"
