# configuration file for project
sample_list : "config/samples.csv"
temp_folder : "/home/moritz/temp/LTS-BiodiversityAnalysisCAO_COI/"
out_folder : "/home/moritz/data/LTS-BiodiversityAnalysisCAO_COI/"
fastp :
  complexity_threshold : 30
mappings_list : "config/mappings.csv"
mappings:
  genomes:
    all_assms_unmasked_w_additional_sp: "/crex/proj/uppstore2017149/BioDiversityAnalysisCAO/nbis/animal_genomes/unmasked/all_assms_unmasked_w_additional_sp.fasta"