# configuration file for project
sample_list : "config/samples.csv"
out_folder : "/crex/proj/uppstore2017149/BioDiversityAnalysisCAO/LTS-BiodiversityAnalysisCAO"
mappers:
  - "minimap2"
fastp :
  complexity_threshold : 30
mappings_list : "config/mappings.csv"
mappings:
  genomes:
    target_species:
      fasta: "resources/genome_index/target_species/target_species.fasta"
      taxon_table: "resources/genome_index/target_species/taxon_table.csv"

blast:
  db: "/sw/data/blast_databases/nt"
  evalue: 1e-30
  max_target_seqs: 200


bwa-mem2:
  threads: 10

bowtie2:
  threads: 8

minimap2:
  threads: 8
  split_num: 4

sintax:
  cutoff: 0.8
  db: "resources/sintax/coi_db_sintax_sp_220218.fasta"
