# configuration file for project
sample_list : "config/samples.csv"
out_folder : "/crex/proj/uppstore2017149/BioDiversityAnalysisCAO/LTS-BiodiversityAnalysisCAO"
mappers:
  - "bwa-mem2"
  - "bowtie2"
  - "minimap2"
fastp :
  complexity_threshold : 30
mappings_list : "config/mappings.csv"
mappings:
  genomes:
    all_assms_unmasked_w_additional_sp: "/crex/proj/uppstore2017149/BioDiversityAnalysisCAO/nbis/animal_genomes/unmasked/all_assms_unmasked_w_additional_sp.fasta"

bwa-mem2:
  threads: 10

bowtie2:
  threads: 10

minimap2:
  threads: 10
  split_num: 4

sintax:
  cutoff: 0.8
  db: "resources/sintax/coi_db_sintax_sp_220218.fasta"
