# configuration file for project
sample_list : "config/samples.csv"
results_dir: "results"
mappers:
  - "minimap2"
fastp :
  complexity_threshold : 30
mappings_list : "config/mappings.csv"
lib_type_to_map: ["DNA"]
mappings:
  genomes:
    target_species:
      fasta: "resources/genome_index/target_species/target_species.fasta"
      taxon_table: "resources/genome_index/target_species/taxon_table.csv"

blast:
  db: "/sw/data/blast_databases/nt"
  evalue: 1e-30
  max_target_seqs: 200

bowtie2:
  threads: 20

minimap2:
  threads: 20
  split_num: 4

sintax:
  cutoff: 0.8
  ranks: ["domain", "kingdom", "phylum", "class", "order", "family", "genus", "species"]
  replace_ranks: ["domain=kingdom", "kingdom=phylum", "phylum=class", "class=order", "order=family", "family=genus", "genus=species", "species=bold_id"]
  db: "resources/sintax/coidb_221216.extra.sintax.fasta"
