$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:
  results_dir:
    type: string
    description: "results output directory"
    default: "results"
  sample_list:
    type: string
    description: "list of samples with fastq paths"
    default: "config/samples.csv"
  lib_type_to_map:
    type: array
    description: "What library type should be mapped to genomes"
    default: ["DNA"]
    items:
      enum: ["DNA"]
  min_ani_cutoff:
    type: integer
    description: "minimum ANI cutoff to use in first read filtering"
    default: 80
  min_align_len:
    type: integer
    description: "minimum aligned length to use in first read filtering"
    default: 30
  mappers:
    type: array
    description: "list of mapping tools to use"
    default: ["bowtie2"]
    items:
      type: string
      enum: ["bowtie2", "bwa-mem2", "minimap2"]
  mappings:
    type: object
    description: "Mapping parameters including reference path and taxa table"
    properties:
      genomes:
        type: object
        description: "Genome mapping parameters"
        additionalProperties:
          type: object
          properties:
            fasta:
              type: string
              description: "Path to fasta file for genome database"
            taxon_table:
              type: string
              description: "Path to taxon table for genome database"
            to_include:
              type: string
              description: "Path to bed file for filtering genome database"
      marker_genes:
        type: object
        description: "Marker gene mapping parameters"
        additionalProperties:
          type: object
          properties:
            fasta:
              type: string
              description: "Path to fasta file for marker gene database"
            ani_cutoff:
              type: integer
              description: "Minimum ANI cutoff to use in first read filtering"
              default: 90
            min_len:
              type: integer
              description: "Minimum aligned length to use in first read filtering"
              default: 80
  krakenuniq:
    type: object
    default:
      db: "/sw/data/KrakenUniq_data/prebuilt/krakendb-2022-06-16-STANDARD"
      exclude: [2,2157]
    properties:
      db:
        type: string
        description: "path to a krakenuniq database"
      exclude:
        type: array
        description: "list of taxonomy ids to exclude"
        items:
          type: integer

  blast:
    type: object
    default:
      db: "/sw/data/blast_databases/nt"
      evalue: 1e-30
      max_target_seqs: 200
      threads: 20
    properties:
      threads:
        type: integer
        description: "Threads to use for blastn"
        default: 20
      db:
        type: string
        description: "Path to blast database (excluding suffix)"
      evalue:
        type: string
        default: 1e-30
        description: "E-value to use in blast search"
      max_target_seqs:
        type: integer
        default: 200
        description: "Max target seqs to report for blast search"
  fastp:
    type: object
    default:
      settings: "-z 9"
      complexity_threshold: 30
      min_length: 30
    properties:
      settings:
        type: string
        default: "-z 9"
        description: "Extra settings to pass to fastp"
      complexity_threshold:
        type: integer
        default: 30
        description: "complexity threshold for fastp"
      min_length:
        type: integer
        default: 30
        description: "Minimum read length in fastp QC"
  bowtie2:
    type: object
    default:
      threads: 20
    properties:
      threads:
        type: integer
        description: "threads for bowtie2"
        default: 20
  minimap2:
    type: object
    default:
      threads: 20
      split_num: 4
    properties:
      threads:
        type: integer
        description: "threads for minimap2"
        default: 20
      split_num:
        type: integer
        description: "split index for every ~NUM input bases"
        default: 4

  sintax:
    type: object
    default:
      cutoff: 0.8
      ranks: ["kingdom", "phylum", "class", "order", "family", "genus", "species"]
      replace_ranks: []
    properties:
      cutoff:
        type: number
        description: "cutoff value for sintax"
        default: 0.8
      db:
        type: string
        description: "path to sintax database fasta file"
        default: ""
      ranks:
        type: array
        description: "ranks to use for parsing in sintax"
        default: ["domain", "kingdom", "phylum", "class", "order", "family", "genus", "species"]
      replace_ranks:
        type: array
        description: "replacement keys for taxonomic ranks"
        default: []
  coinr:
    type: object
    default:
      dbname: "COInr"
    properties:
      dbname:
        type: string
        description: "Base name of COInr db"
        default: "COInr"

required:
  - sample_list