name: testing

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
    branches:
      - '*'

env:
  TMPDIR: /tmp

defaults:
  run:
    shell: bash -l {0}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: "."
          snakefile: "workflow/Snakefile"
          args: "--lint"
  testrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@main
        with:
          environment-file: environment.yml
          cache-env: true
      - name: Test run
        run: |
          mkdir -p test/data
          touch test/data/sample{1,2}.R{1,2}.fastq.gz test/data/target_species.fasta test/data/to_include.bed test/data/taxon_table.csv test/data/coidb.fasta
          snakemake --profile test -n
  
