name: testing

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
    branches:
      - '*'

env:
  TMPDIR: /tmp

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: "."
          snakefile: "workflow/Snakefile"
          args: "--lint"
  testrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1.1.1
      - name: Install the conda environment
        run: conda env update -n base -f environment.yml
      - name: Perform test run
        run: snakemake --profile test -c 4
  
