name: testing

on:
  workflow_dispatch:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

env:
  TMPDIR: /tmp

jobs:
  testrun:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1.1.1
    - name: Install the conda environment
      run: conda env update -n base -f environment.yml
    - name: Lint
      run: snakemake --lint
    - name: Perform test run 
      run: snakemake --profile test -c 4
  
